workflows:
  android-workflow:
    name: CalcMaster Production Build

    max_build_duration: 60

    environment:
      java: 17

      vars:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m"

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Show project structure
        script: ls -R

      - name: Grant execute permission
        script: chmod +x gradlew

      - name: Clean project
        script: ./gradlew clean

      - name: Download dependencies
        script: ./gradlew dependencies

      - name: Build Debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - prince.ar.abdur.rahman2008@gmail.com
