workflows:
  android-workflow:
    name: CalcMaster Android Build

    max_build_duration: 60

    environment:
      java: 17

      vars:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m"

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Checkout info
        script: ls -la

      - name: Make gradlew executable
        script: chmod +x gradlew

      - name: Clean project
        script: ./gradlew clean

      - name: Download dependencies
        script: ./gradlew dependencies

      - name: Build Debug APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/*.apk

    publishing:
      email:
        recipients:
          - prince.ar.abdur.rahman2008@gmail.com
