workflows:
  android-workflow:
    name: CalcMaster Fixed APK Build

    max_build_duration: 90

    environment:
      java: 17

      vars:
        GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096m"

    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

    scripts:
      - name: Show project
        script: ls -R

      - name: Make gradlew executable
        script: chmod +x gradlew || true

      - name: Clean build
        script: ./gradlew clean

      - name: Build APK
        script: ./gradlew assembleDebug

      - name: Find APK location (DEBUG)
        script: find . -name "*.apk" -type f

    artifacts:
      - "**/*.apk"

    publishing:
      email:
        recipients:
          - prince.ar.abdur.rahman2008@gmail.com
